Repository LucasTesnier/ZAAAAAAAAAAAAppy, pull requests merged in 2022-06, with the labels that each got.

#57 GUI/architecture/53
  .gitignore
  CMakeLists.txt
  cmake/FindSFML.cmake
  graph.png
  src/zappy_gui/CMakeLists.txt
  src/zappy_gui/Core/CMakeLists.txt
  src/zappy_gui/Core/Core.cpp
  src/zappy_gui/Core/Core.hpp
  src/zappy_gui/Core/Network/CMakeLists.txt
  src/zappy_gui/Core/SFML/CMakeLists.txt
  src/zappy_gui/Core/SFML/Interface/CMakeLists.txt
  src/zappy_gui/Core/SFML/Interface/Interface.cpp
  src/zappy_gui/Core/SFML/Interface/Interface.hpp
  src/zappy_gui/Core/SFML/Map/CMakeLists.txt
  src/zappy_gui/Core/SFML/Map/Map.cpp
  src/zappy_gui/Core/SFML/Map/Map.hpp
  src/zappy_gui/Core/SFML/SFML.cpp
  src/zappy_gui/Core/SFML/SFML.hpp
  src/zappy_gui/main.cpp
Labels: Pull Request

#59 ClientAI - Wrapped All functions for the communication between IA and Server, close #22
  .gitignore
  src/zappy_ai/ai_DLLib_wrapper.py
  src/zappy_ai/ai_function_wrapper.py
  src/zappy_ai/zappy_ai
Labels: Documentation, Implementing

#65 GUI/event handling/58
  src/zappy_gui/Core/SFML/CMakeLists.txt
  src/zappy_gui/Core/SFML/WrapperSFML/CMakeLists.txt
  src/zappy_gui/Core/SFML/WrapperSFML/Event.hpp
Labels: Pull Request

#63 Utils/gitignore
  .gitignore
Labels: Pull Request

#69 GUI - SFML
  src/zappy_gui/Core/SFML/SFML.cpp
  src/zappy_gui/Core/SFML/SFML.hpp
  src/zappy_gui/Core/SFML/WrapperSFML/CMakeLists.txt
Labels: Pull Request

#60 9/Network/Loop - Implement Server Network
  .gitignore
  Doxyfile
  docs/doxygen-awesome.css
  src/CMakeLists.txt
  src/zappy_ai/CMakeLists.txt
  src/zappy_ai_src/CMakeLists.txt
  src/zappy_ai_src/ai_DLLib_wrapper.py
  src/zappy_ai_src/ai_function_wrapper.py
  src/zappy_ai_src/zappyAIArgumentsTester.sh
  src/zappy_ai_src/zappy_ai
  src/zappy_server/CMakeLists.txt
  src/zappy_server_src/CMakeLists.txt
  src/zappy_server_src/core/CMakeLists.txt
  src/zappy_server_src/core/auth_command.c
  src/zappy_server_src/core/command_hold.c
  src/zappy_server_src/core/include/command_hold.h
  src/zappy_server_src/core/include/entrypoint.h
  src/zappy_server_src/core/include/my_zappy_server.h
  src/zappy_server_src/core/include/rcodes.h
  src/zappy_server_src/core/include/server.h
  src/zappy_server_src/core/my_zappy_server.c
  src/zappy_server_src/core/server_data.c
  src/zappy_server_src/core/server_run.c
  src/zappy_server_src/entrypoint.c
  src/zappy_server_src/net_utils/CMakeLists.txt
  src/zappy_server_src/net_utils/display_utils.c
  src/zappy_server_src/net_utils/fd_sets_manage/CMakeLists.txt
  src/zappy_server_src/net_utils/fd_sets_manage/fd_set_manage.h
  src/zappy_server_src/net_utils/fd_sets_manage/fd_sets_manage.c
  src/zappy_server_src/net_utils/fd_sets_manage/server_accept_new_client.c
  src/zappy_server_src/net_utils/fd_sets_manage/server_close_client.c
  src/zappy_server_src/net_utils/fd_sets_manage/server_read_client.c
  src/zappy_server_src/net_utils/fd_sets_manage/server_write_client.c
  src/zappy_server_src/net_utils/include/net_utils.h
  src/zappy_server_src/net_utils/peer.c
  src/zappy_server_src/net_utils/select.c
  src/zappy_server_src/net_utils/tcp_server.c
Labels: Documentation, Pull Request, Refactoring, Implementing

#71 50/Server - Arguments
  src/zappy_server_src/core/CMakeLists.txt
  src/zappy_server_src/core/argument_handling.c
  src/zappy_server_src/core/include/argument_handling.h
  src/zappy_server_src/core/include/server.h
  src/zappy_server_src/core/my_zappy_server.c
  src/zappy_server_src/core/server_data.c
  src/zappy_server_src/core/server_run.c
Labels: Pull Request, Implementing

#73 8/Server - Listen
  src/zappy_server_src/core/argument_handling.c
  src/zappy_server_src/core/include/my_zappy_server.h
  src/zappy_server_src/core/my_zappy_server.c
  src/zappy_server_src/core/server_data.c
  src/zappy_server_src/net_utils/include/net_utils.h
  src/zappy_server_src/net_utils/tcp_server.c
Labels: Pull Request, Refactoring, Implementing

#75 14/ClientAI - Network API
  .gitignore
  src/zappy_ai_src/CMakeLists.txt
  src/zappy_ai_src/network/CMakeLists.txt
  src/zappy_ai_src/network/api/CMakeLists.txt
  src/zappy_ai_src/network/api/authentification.c
  src/zappy_ai_src/network/api/include/api.h
  src/zappy_ai_src/network/api/include/intern_data.h
  src/zappy_ai_src/network/entrypoint.c
  src/zappy_ai_src/network/net_utils/CMakeLists.txt
  src/zappy_ai_src/network/net_utils/client_utils.c
  src/zappy_ai_src/network/net_utils/fetch_message.c
  src/zappy_ai_src/network/net_utils/include/client_utils.h
  src/zappy_ai_src/network/net_utils/include/internals.h
  src/zappy_ai_src/network/net_utils/manage_fd_sets.c
  src/zappy_ai_src/network/net_utils/send_message.c
  src/zappy_ai_src/network/net_utils/update_client.c
Labels: Pull Request, Implementing

#72 Server - App - Implement scheduler module
  .gitignore
  src/zappy_server_src/core/CMakeLists.txt
  src/zappy_server_src/core/include/scheduler/scheduler.h
  src/zappy_server_src/core/scheduler.c
Labels: Pull Request, Server - App

#70 GUI - Parser
  .gitignore
  src/CMakeLists.txt
  src/zappy_gui/Core/Core.cpp
  src/zappy_gui/Core/Core.hpp
  src/zappy_gui/main.cpp
  src/zappy_gui_src/CMakeLists.txt
  src/zappy_gui_src/Core/CMakeLists.txt
  src/zappy_gui_src/Core/Core.cpp
  src/zappy_gui_src/Core/Core.hpp
  src/zappy_gui_src/Core/Network/CMakeLists.txt
  src/zappy_gui_src/Core/SFML/CMakeLists.txt
  src/zappy_gui_src/Core/SFML/Interface/CMakeLists.txt
  src/zappy_gui_src/Core/SFML/Interface/Interface.cpp
  src/zappy_gui_src/Core/SFML/Interface/Interface.hpp
  src/zappy_gui_src/Core/SFML/Map/CMakeLists.txt
  src/zappy_gui_src/Core/SFML/Map/Map.cpp
  src/zappy_gui_src/Core/SFML/Map/Map.hpp
  src/zappy_gui_src/Core/SFML/SFML.cpp
  src/zappy_gui_src/Core/SFML/SFML.hpp
  src/zappy_gui_src/Core/SFML/WrapperSFML/CMakeLists.txt
  src/zappy_gui_src/Core/SFML/WrapperSFML/Event.hpp
  src/zappy_gui_src/Exception/CMakeLists.txt
  src/zappy_gui_src/Exception/ZappyGuiException.cpp
  src/zappy_gui_src/Exception/ZappyGuiException.hpp
  src/zappy_gui_src/main.cpp
Labels: Pull Request

#78 11/Server - Request Queue
  src/zappy_server_src/net_utils/fd_sets_manage/server_read_client.c
Labels: Bug, Pull Request, Refactoring

#80 12/ClientGUI - Network API
  .gitignore
  src/zappy_gui_src/CMakeLists.txt
  src/zappy_gui_src/network/CMakeLists.txt
  src/zappy_gui_src/network/api/CMakeLists.txt
  src/zappy_gui_src/network/api/ask/restart.c
  src/zappy_gui_src/network/api/authentification.c
  src/zappy_gui_src/network/api/get/restart.c
  src/zappy_gui_src/network/api/get/retcode.c
  src/zappy_gui_src/network/api/get/state.c
  src/zappy_gui_src/network/api/get/unexpected.c
  src/zappy_gui_src/network/api/include/api.h
  src/zappy_gui_src/network/api/include/intern_data.h
  src/zappy_gui_src/network/entrypoint.c
  src/zappy_gui_src/network/net_utils/CMakeLists.txt
  src/zappy_gui_src/network/net_utils/client_utils.c
  src/zappy_gui_src/network/net_utils/fetch_message.c
  src/zappy_gui_src/network/net_utils/include/client_utils.h
  src/zappy_gui_src/network/net_utils/include/internals.h
  src/zappy_gui_src/network/net_utils/manage_fd_sets.c
  src/zappy_gui_src/network/net_utils/send_message.c
  src/zappy_gui_src/network/net_utils/update_client.c
  src/zappy_server_src/core/include/rcodes.h
Labels: Pull Request, Implementing

#76 Architecure/Implement data structures
  src/zappy_server_src/core/CMakeLists.txt
  src/zappy_server_src/core/container_utils.c
  src/zappy_server_src/core/entity/CMakeLists.txt
  src/zappy_server_src/core/entity/egg.c
  src/zappy_server_src/core/entity/entity.c
  src/zappy_server_src/core/entity/player.c
  src/zappy_server_src/core/entity/tile.c
  src/zappy_server_src/core/include/container.h
  src/zappy_server_src/core/include/container_manip.h
  src/zappy_server_src/core/include/entity/eggs.h
  src/zappy_server_src/core/include/entity/entity.h
  src/zappy_server_src/core/include/entity/entity_types.h
  src/zappy_server_src/core/include/entity/player.h
  src/zappy_server_src/core/include/entity/tile.h
Labels: Pull Request, Server - App

#81 GUI - Implement Tile class
  src/zappy_gui_src/Core/SFML/Map/CMakeLists.txt
  src/zappy_gui_src/Core/SFML/Map/Tile.cpp
  src/zappy_gui_src/Core/SFML/Map/Tile.hpp
Labels: Pull Request

#88 ClientAI - Find the Ip corresponding to the hostname
  .gitignore
  src/zappy_ai_src/CMakeLists.txt
  src/zappy_ai_src/ai_DLLib_wrapper.py
  src/zappy_ai_src/network/CMakeLists.txt
  src/zappy_ai_src/zappy_ai
Labels: Pull Request, Implementing

#85 G UI/map/4
  assets/season1_ground1.png
  src/zappy_gui_src/Core/SFML/Map/Map.cpp
  src/zappy_gui_src/Core/SFML/Map/Map.hpp
  src/zappy_gui_src/Core/SFML/Map/Tile.cpp
  src/zappy_gui_src/Core/SFML/Map/Tile.hpp
  src/zappy_gui_src/Core/SFML/SFML.cpp
  src/zappy_gui_src/Core/SFML/SFML.hpp
Labels: Pull Request

#96 Architecture/init teams in server data
  .gitignore
  CMakeLists.txt
  src/zappy_ai_src/network/api/get/retcode.c
  src/zappy_gui_src/network/api/CMakeLists.txt
  src/zappy_server_src/core/CMakeLists.txt
  src/zappy_server_src/core/auth_command.c
  src/zappy_server_src/core/cmake_error.c
  src/zappy_server_src/core/entity/CMakeLists.txt
  src/zappy_server_src/core/entity/egg.c
  src/zappy_server_src/core/entity/entity.c
  src/zappy_server_src/core/entity/entity_delete.c
  src/zappy_server_src/core/entity/entity_wrapper.c
  src/zappy_server_src/core/entity/entity_wrapper_add.c
  src/zappy_server_src/core/entity/entity_wrapper_remove.c
  src/zappy_server_src/core/entity/player.c
  src/zappy_server_src/core/entity/tile.c
  src/zappy_server_src/core/include/command_hold.h
  src/zappy_server_src/core/include/entity/eggs.h
  src/zappy_server_src/core/include/entity/entity.h
  src/zappy_server_src/core/include/entity/player.h
  src/zappy_server_src/core/include/entity/tile.h
  src/zappy_server_src/core/include/map.h
  src/zappy_server_src/core/include/rcodes.h
  src/zappy_server_src/core/include/scheduler/scheduler.h
  src/zappy_server_src/core/include/server.h
  src/zappy_server_src/core/include/team.h
  src/zappy_server_src/core/map.c
  src/zappy_server_src/core/server_data.c
  src/zappy_server_src/core/server_init.c
  src/zappy_server_src/core/server_run.c
  src/zappy_server_src/core/team.c
  src/zappy_server_src/core/teams_remove.c
  src/zappy_server_src/entrypoint.c
  tests/unit_tests/CMakeLists.txt
  tests/unit_tests/wrapper/CMakeLists.txt
  tests/unit_tests/wrapper/wrapper_tests.c
Labels: Pull Request, Server - App

#94 ClientAI - CoreClient
  src/zappy_ai_src/ai_DLLib_wrapper.py
  src/zappy_ai_src/ai_core.py
  src/zappy_ai_src/ai_function_wrapper.py
  src/zappy_ai_src/zappy_ai
Labels: Pull Request, Implementing

#99 Server commands/join
  src/zappy_server_src/core/CMakeLists.txt
  src/zappy_server_src/core/commands/CMakeLists.txt
  src/zappy_server_src/core/commands/auth_command.c
  src/zappy_server_src/core/entity/CMakeLists.txt
  src/zappy_server_src/core/entity/entity_wrapper_add.c
  src/zappy_server_src/core/entity/entity_wrapper_create.c
  src/zappy_server_src/core/include/entity/entity.h
  src/zappy_server_src/core/server_init.c
  tests/unit_tests/wrapper/wrapper_tests.c
Labels: Pull Request, Server - App

#102 [*] Fix auth_command.c bad merge
  src/zappy_server_src/core/commands/auth_command.c
Labels: Pull Request, Refactoring, Server - App

#93 ClientAI - Minor Adds
  src/zappy_ai_src/ai_function_wrapper.py
  src/zappy_ai_src/ai_handle_response.py
Labels: Pull Request, Implementing

#104 103/Server Scheduler Ending
  src/zappy_server_src/core/command_hold.c
  src/zappy_server_src/core/include/command_hold.h
  src/zappy_server_src/core/include/server.h
  src/zappy_server_src/core/server_data.c
  src/zappy_server_src/core/server_run.c
Labels: Implementing

#90 GUI/Pack/3
  src/zappy_gui_src/Core/Network/CMakeLists.txt
  src/zappy_gui_src/Core/Network/Unpack.cpp
  src/zappy_gui_src/Core/Network/Unpack.hpp
  src/zappy_gui_src/Core/SFML/SFML.cpp
  src/zappy_gui_src/Exception/ZappyGuiException.hpp
  src/zappy_server_src/core/entity/CMakeLists.txt
  src/zappy_server_src/core/entity/pack.c
  src/zappy_server_src/core/entity/pack_get_len.c
  src/zappy_server_src/core/include/entity/pack.h
  zappy_gui_test
Labels: Documentation, Pull Request, Implementing, Server - App

#101 GUI - Menu - Interface
  src/zappy_gui_src/Core/SFML/Interface/Interface.cpp
  src/zappy_gui_src/Core/SFML/Interface/Interface.hpp
  src/zappy_gui_src/Core/SFML/SFML.cpp
  src/zappy_gui_src/Core/SFML/SFML.hpp
Labels: Pull Request

#97 GUI - Map - Optimisation
  src/zappy_gui_src/Core/Core.cpp
  src/zappy_gui_src/Core/SFML/Map/Map.cpp
  src/zappy_gui_src/Core/SFML/Map/Map.hpp
  src/zappy_gui_src/Core/SFML/Map/Tile.cpp
  src/zappy_gui_src/Core/SFML/Map/Tile.hpp
  src/zappy_gui_src/Core/SFML/SFML.cpp
Labels: Pull Request, Implementing

#107 105/Serer - Select Timing
  src/zappy_server_src/core/command_hold.c
  src/zappy_server_src/core/commands/CMakeLists.txt
  src/zappy_server_src/core/commands/auth_command.c
  src/zappy_server_src/core/commands/inventory_command.c
  src/zappy_server_src/core/include/command_hold.h
  src/zappy_server_src/core/include/rcodes.h
  src/zappy_server_src/core/include/scheduler/scheduler.h
  src/zappy_server_src/core/scheduler.c
  src/zappy_server_src/core/server_run.c
  src/zappy_server_src/net_utils/include/net_utils.h
  src/zappy_server_src/net_utils/select.c
Labels: Bug, Implementing

#108 Server commands/inventory
  src/zappy_server_src/core/commands/inventory_command.c
  src/zappy_server_src/core/container_utils.c
  src/zappy_server_src/core/include/container.h
  zappy_gui_test
Labels: Pull Request, Server - App

#112 89/Server - API AI
  src/zappy_ai_src/network/api/CMakeLists.txt
  src/zappy_ai_src/network/api/ask/look.c
  src/zappy_ai_src/network/api/ask/turn.c
  src/zappy_ai_src/network/api/get/forward.c
  src/zappy_ai_src/network/api/get/look.c
  src/zappy_ai_src/network/api/get/retcode.c
  src/zappy_ai_src/network/api/get/turn.c
  src/zappy_ai_src/network/api/include/api.h
  src/zappy_ai_src/network/entrypoint.c
  src/zappy_server_src/core/argument_handling.c
  src/zappy_server_src/core/command_hold.c
  src/zappy_server_src/core/commands/CMakeLists.txt
  src/zappy_server_src/core/commands/look_command.c
  src/zappy_server_src/core/commands/turn_command.c
  src/zappy_server_src/core/include/command_hold.h
  src/zappy_server_src/core/include/rcodes.h
  src/zappy_server_src/core/include/server.h
  src/zappy_server_src/core/server_run.c
Labels: Implementing

#111 [+] Add forward command support
  src/zappy_server_src/core/commands/forward_command.c
Labels: Pull Request, Server - App

#115 89/Server - API AI
  src/zappy_ai_src/network/api/CMakeLists.txt
  src/zappy_ai_src/network/api/get/retcode.c
  src/zappy_ai_src/network/api/get/unexpected.c
  src/zappy_ai_src/network/api/include/api.h
  src/zappy_ai_src/network/entrypoint.c
  src/zappy_server_src/core/argument_handling.c
  src/zappy_server_src/core/command_hold.c
  src/zappy_server_src/core/commands/CMakeLists.txt
  src/zappy_server_src/core/commands/connectnbr_command.c
  src/zappy_server_src/core/commands/eject_command.c
  src/zappy_server_src/core/commands/forward_command.c
  src/zappy_server_src/core/commands/place_command.c
  src/zappy_server_src/core/commands/take_command.c
  src/zappy_server_src/core/commands/turn_command.c
  src/zappy_server_src/core/commands/unexpected_send.c
  src/zappy_server_src/core/entity/player.c
  src/zappy_server_src/core/include/command_hold.h
  src/zappy_server_src/core/include/rcodes.h
  src/zappy_server_src/core/map.c
Labels: Implementing

#110 ClientAI - Minor Adds
  src/zappy_ai_src/ai_core.py
  src/zappy_ai_src/ai_function_wrapper.py
Labels: Documentation, Pull Request, Implementing

#113 G UI/Pack/3
  .gitignore
  assets/apple.png
  src/zappy_gui_src/Core/Network/CMakeLists.txt
  src/zappy_gui_src/Core/Network/Unpack.cpp
  src/zappy_gui_src/Core/Network/Unpack.hpp
Labels: Documentation, Pull Request, Implementing

#117 [+] Call entity_wrapper_destroy when exiting server loop
  src/zappy_server_src/core/commands/turn_command.c
  src/zappy_server_src/core/server_data.c
Labels: Server - App

#98 GUI - Menu - minimap - 31
  src/zappy_gui_src/Core/SFML/Interface/CMakeLists.txt
  src/zappy_gui_src/Core/SFML/Interface/Interface.cpp
  src/zappy_gui_src/Core/SFML/Interface/Interface.hpp
  src/zappy_gui_src/Core/SFML/Interface/Minimap/CMakeLists.txt
  src/zappy_gui_src/Core/SFML/Interface/Minimap/Minimap.cpp
  src/zappy_gui_src/Core/SFML/Interface/Minimap/Minimap.hpp
  src/zappy_gui_src/Core/SFML/Map/Map.cpp
  src/zappy_gui_src/Core/SFML/SFML.cpp
  src/zappy_gui_src/Core/SFML/SFML.hpp
Labels: Pull Request

#119 89/Server - GUI API
  src/zappy_ai_src/network/api/get/unexpected.c
  src/zappy_gui_src/Core/Network/CMakeLists.txt
  src/zappy_gui_src/Core/Network/api/authentification.c
  src/zappy_gui_src/Core/Network/api/get/restart.c
  src/zappy_gui_src/Core/Network/api/get/retcode.c
  src/zappy_gui_src/Core/Network/api/get/unexpected.c
  src/zappy_gui_src/Core/Network/api/include/intern_data.h
  src/zappy_gui_src/Core/Network/entrypoint.c
  src/zappy_gui_src/Core/Network/net_utils/fetch_message.c
  src/zappy_gui_src/Core/Network/net_utils/include/client_utils.h
  src/zappy_server_src/core/commands/CMakeLists.txt
  src/zappy_server_src/core/commands/auth_command.c
  src/zappy_server_src/core/commands/broadcast_command.c
  src/zappy_server_src/core/commands/eject_command.c
  src/zappy_server_src/core/commands/fork_command.c
  src/zappy_server_src/core/commands/forward_command.c
  src/zappy_server_src/core/commands/game_status.c
  src/zappy_server_src/core/commands/incantation_command.c
  src/zappy_server_src/core/commands/inventory_command.c
  src/zappy_server_src/core/commands/look_command.c
  src/zappy_server_src/core/commands/map_info.c
  src/zappy_server_src/core/commands/place_command.c
  src/zappy_server_src/core/commands/take_command.c
  src/zappy_server_src/core/commands/turn_command.c
  src/zappy_server_src/core/entity/pack.c
  src/zappy_server_src/core/include/command_hold.h
  src/zappy_server_src/core/include/rcodes.h
  src/zappy_server_src/core/include/scheduler/scheduler.h
  src/zappy_server_src/core/scheduler.c
  src/zappy_server_src/core/server_run.c
  src/zappy_server_src/net_utils/include/net_utils.h
Labels: Bug, Pull Request, Refactoring, Implementing

#118 GUI/menu/inventory/30
  src/zappy_gui_src/Core/SFML/Interface/CMakeLists.txt
  src/zappy_gui_src/Core/SFML/Interface/Interface.cpp
  src/zappy_gui_src/Core/SFML/Interface/Interface.hpp
  src/zappy_gui_src/Core/SFML/Interface/Inventory/CMakeLists.txt
  src/zappy_gui_src/Core/SFML/Interface/Inventory/Inventory.cpp
  src/zappy_gui_src/Core/SFML/Interface/Inventory/Inventory.hpp
  src/zappy_gui_src/Core/SFML/Interface/Minimap/Minimap.cpp
  src/zappy_gui_src/Core/SFML/Interface/Minimap/Minimap.hpp
Labels: Pull Request

#122 Hotfix/call entity wrapper dtor
  src/zappy_server_src/core/CMakeLists.txt
  src/zappy_server_src/core/entity/entity_delete.c
  src/zappy_server_src/core/entity/entity_wrapper.c
  src/zappy_server_src/core/include/scheduler/scheduler.h
  src/zappy_server_src/core/scheduler_delete.c
  src/zappy_server_src/core/server_data.c
  src/zappy_server_src/core/teams_remove.c
Labels: Bug, Server - App

#125 [*] Fix negative coord calc when /forward or /eject
  src/zappy_server_src/core/commands/eject_command.c
  src/zappy_server_src/core/commands/forward_command.c
Labels: Bug, Pull Request, Server - App

#121 GUI/menu/server/29
  assets/arial.ttf
  src/zappy_gui_src/Core/SFML/Interface/CMakeLists.txt
  src/zappy_gui_src/Core/SFML/Interface/Interface.cpp
  src/zappy_gui_src/Core/SFML/Interface/Interface.hpp
  src/zappy_gui_src/Core/SFML/Interface/Inventory/Inventory.cpp
  src/zappy_gui_src/Core/SFML/Interface/Inventory/Inventory.hpp
  src/zappy_gui_src/Core/SFML/Interface/ServerCommunication/CMakeLists.txt
  src/zappy_gui_src/Core/SFML/Interface/ServerCommunication/ServerCommunication.cpp
  src/zappy_gui_src/Core/SFML/Interface/ServerCommunication/ServerCommunication.hpp
  src/zappy_gui_src/Exception/ZappyGuiException.cpp
  src/zappy_gui_src/Exception/ZappyGuiException.hpp
Labels: Pull Request

#127 89/Server - APIGUI
  src/zappy_ai_src/network/entrypoint.c
  src/zappy_server_src/core/CMakeLists.txt
  src/zappy_server_src/core/commands/forward_command.c
  src/zappy_server_src/core/commands/incantation_command.c
  src/zappy_server_src/core/commands/join_command.c
  src/zappy_server_src/core/commands/look_command.c
  src/zappy_server_src/core/commands/unexpected_send.c
  src/zappy_server_src/core/entity/entity_wrapper_remove.c
  src/zappy_server_src/core/entity/tile.c
  src/zappy_server_src/core/include/command_hold.h
  src/zappy_server_src/core/include/container.h
  src/zappy_server_src/core/include/entity/tile.h
  src/zappy_server_src/core/include/map.h
  src/zappy_server_src/core/include/rcodes.h
  src/zappy_server_src/core/include/scheduler/scheduler.h
  src/zappy_server_src/core/map.c
  src/zappy_server_src/core/player_life.c
  src/zappy_server_src/core/ressource_generation.c
  src/zappy_server_src/core/scheduler.c
  src/zappy_server_src/core/scheduler_delete.c
  src/zappy_server_src/core/server_run.c
Labels: Implementing

#130 129/GUI - Communication
  src/zappy_gui_src/Core/CMakeLists.txt
  src/zappy_gui_src/Core/Core.cpp
  src/zappy_gui_src/Core/Core.hpp
  src/zappy_gui_src/Core/Network/Unpack.cpp
  src/zappy_gui_src/Core/Network/Unpack.hpp
  src/zappy_gui_src/Core/SFML/SFML.cpp
  src/zappy_gui_src/Core/SFML/SFML.hpp
  src/zappy_server_src/core/commands/start_information.c
Labels: Implementing

#132 [+] Fix entity wrapper deleting player when changing tile
  src/zappy_server_src/core/commands/forward_command.c
  src/zappy_server_src/core/entity/entity_delete.c
  src/zappy_server_src/core/entity/entity_wrapper.c
  src/zappy_server_src/core/entity/tile.c
  src/zappy_server_src/core/server_run.c
Labels: Bug, Pull Request, Server - App

#133 ClientAI - Server Link
  src/zappy_ai_src/ai_core.py
  src/zappy_ai_src/ai_strategy_management.py
  src/zappy_server_src/core/commands/look_command.c
  src/zappy_server_src/core/server_run.c
Labels: Documentation, Pull Request, Implementing

#134 89/Server - End Game
  src/zappy_server_src/core/commands/join_command.c
  src/zappy_server_src/core/player_life.c
  src/zappy_server_src/core/team.c
Labels: Implementing

#137 make some changes to make clearer the code than before #136
  src/zappy_gui_src/Core/Core.cpp
  src/zappy_gui_src/Core/Core.hpp
  src/zappy_gui_src/Core/Network/Unpack.cpp
  src/zappy_gui_src/Core/SFML/Map/CMakeLists.txt
  src/zappy_gui_src/Core/SFML/Map/Map.cpp
  src/zappy_gui_src/Core/SFML/Map/Map.hpp
  src/zappy_gui_src/Core/SFML/Map/Tile.cpp
  src/zappy_gui_src/Core/SFML/Map/Tile.hpp
  src/zappy_gui_src/Core/SFML/SFML.cpp
  src/zappy_gui_src/Exception/ZappyGuiException.cpp
  src/zappy_gui_src/Exception/ZappyGuiException.hpp
Labels: Pull Request

#135 34 gui map player
  src/zappy_gui_src/Core/CMakeLists.txt
  src/zappy_gui_src/Core/Core.cpp
  src/zappy_gui_src/Core/Core.hpp
  src/zappy_gui_src/Core/Entity/CMakeLists.txt
  src/zappy_gui_src/Core/Entity/Entity.cpp
  src/zappy_gui_src/Core/Entity/Entity.hpp
  src/zappy_gui_src/Core/Network/CMakeLists.txt
  src/zappy_gui_src/Core/Network/Unpack.cpp
  src/zappy_gui_src/Core/Network/Unpack.hpp
  src/zappy_gui_src/Core/SFML/Map/CMakeLists.txt
  src/zappy_gui_src/Core/SFML/Map/Map.cpp
  src/zappy_gui_src/Core/SFML/Map/Map.hpp
  src/zappy_gui_src/Core/SFML/Map/Tile.hpp
  src/zappy_gui_src/Core/SFML/SFML.hpp
Labels: Documentation, Pull Request, Implementing

#138 `fix_get_tile` calculation
  src/zappy_server_src/core/CMakeLists.txt
  src/zappy_server_src/core/commands/eject_command.c
  src/zappy_server_src/core/commands/forward_command.c
  src/zappy_server_src/core/entity/tile.c
  src/zappy_server_src/core/include/map.h
  src/zappy_server_src/core/map_utils.c
Labels: Bug, Pull Request, Server - App

#139 89/Server - Fork Applicatif
  src/zappy_ai_src/network/api/get/retcode.c
  src/zappy_server_src/core/commands/fork_command.c
  src/zappy_server_src/core/commands/inventory_command.c
  src/zappy_server_src/core/commands/join_command.c
  src/zappy_server_src/core/entity/entity_wrapper_create.c
  src/zappy_server_src/core/include/command_hold.h
  src/zappy_server_src/core/include/entity/entity.h
  src/zappy_server_src/core/include/rcodes.h
  src/zappy_server_src/core/server_run.c
  src/zappy_server_src/core/team.c
Labels: Implementing

#141 ClientAI - Error Handling on server connection
  src/zappy_ai_src/ai_core.py
  src/zappy_ai_src/ai_function_wrapper.py
Labels: Pull Request, Implementing

#143 133/APIAI - Network state
  src/zappy_ai_src/network/api/ask/broadcast.c
  src/zappy_ai_src/network/api/ask/connectnbr.c
  src/zappy_ai_src/network/api/ask/eject.c
  src/zappy_ai_src/network/api/ask/fork.c
  src/zappy_ai_src/network/api/ask/forward.c
  src/zappy_ai_src/network/api/ask/incantation.c
  src/zappy_ai_src/network/api/ask/inventory.c
  src/zappy_ai_src/network/api/ask/join.c
  src/zappy_ai_src/network/api/ask/look.c
  src/zappy_ai_src/network/api/ask/place.c
  src/zappy_ai_src/network/api/ask/take.c
  src/zappy_ai_src/network/api/ask/turn.c
Labels: Refactoring, Implementing

#145 134/Server - Logout
  src/zappy_server_src/core/commands/auth_command.c
  src/zappy_server_src/core/commands/entity_info.c
  src/zappy_server_src/core/commands/map_info.c
  src/zappy_server_src/core/commands/start_information.c
  src/zappy_server_src/core/commands/unexpected_send.c
  src/zappy_server_src/core/server_data.c
  src/zappy_server_src/net_utils/fd_sets_manage/server_close_client.c
Labels: Bug, Refactoring

#144 ClientAI - Error Handling when connecting to server
  src/zappy_ai_src/ai_core.py
  src/zappy_ai_src/ai_function_wrapper.py
  src/zappy_ai_src/ai_safe_error.py
  src/zappy_ai_src/ai_strategy_management.py
  src/zappy_ai_src/zappy_ai
Labels: Pull Request, Implementing

#146 GUI/map/entities
  src/zappy_gui_src/Core/Core.cpp
  src/zappy_gui_src/Core/Core.hpp
  src/zappy_gui_src/Core/Network/Unpack.cpp
  src/zappy_gui_src/Core/Network/Unpack.hpp
  src/zappy_gui_src/Core/SFML/Map/CMakeLists.txt
  src/zappy_gui_src/Core/SFML/Map/Map.cpp
  src/zappy_gui_src/Core/SFML/Map/Map.hpp
  src/zappy_gui_src/Core/SFML/Map/Tile.hpp
  src/zappy_gui_src/Core/SFML/SFML.cpp
  src/zappy_gui_src/Core/SFML/SFML.hpp
Labels: Documentation, Pull Request

#149 ClientIA - Flush on all ask functions
  src/zappy_ai_src/ai_function_wrapper.py
Labels: Pull Request, Implementing

#150 GUI/utility/libanimation/91
  src/zappy_gui_src/Core/Animation/Animation.cpp
  src/zappy_gui_src/Core/Animation/Animation.hpp
  src/zappy_gui_src/Core/Animation/CMakeLists.txt
  src/zappy_gui_src/Core/CMakeLists.txt
  src/zappy_gui_src/Exception/ZappyGuiException.cpp
  src/zappy_gui_src/Exception/ZappyGuiException.hpp
Labels: Pull Request

#154 Create wrapper for the AI queues
  src/zappy_ai_src/ai_core.py
  src/zappy_ai_src/ai_function_wrapper.py
  src/zappy_ai_src/ai_queue_wrapper.py
  src/zappy_ai_src/ai_strategy_management.py
Labels: Pull Request, Implementing

#160 142/Server - Drop
  src/zappy_server_src/core/player_life.c
Labels: Bug, Refactoring

#164 142/HotFix - Take
  src/zappy_server_src/core/map.c
  src/zappy_server_src/core/player_life.c
Labels: Bug, Refactoring

#167 142/HotFix - NetUtils Parse
  src/zappy_ai_src/network/entrypoint.c
  src/zappy_server_src/core/commands/join_command.c
  src/zappy_server_src/net_utils/fd_sets_manage/server_read_client.c
  src/zappy_server_src/net_utils/fd_sets_manage/server_write_client.c
  src/zappy_server_src/net_utils/include/net_utils.h
  src/zappy_server_src/net_utils/peer.c
Labels: Bug, Refactoring

#169 [+] remove players and eggs when receiving empty string from the server
  src/zappy_gui_src/Core/Core.cpp
Labels: Implementing

#165 Refactor of handling response in AI queue
  src/zappy_ai_src/ai_queue_wrapper.py
  src/zappy_ai_src/ai_strategy_management.py
Labels: Pull Request, Implementing

#170 142/HotFix - Incantation
  src/zappy_server_src/core/commands/fork_utils.c
  src/zappy_server_src/core/commands/incantation_command.c
  src/zappy_server_src/core/include/incantation.h
  src/zappy_server_src/core/include/remove_inventory.h
Labels: Bug, Refactoring

#174 142/HotFix - Incantation Ejected
  src/zappy_server_src/core/commands/incantation_command.c
  src/zappy_server_src/core/commands/look_command.c
  src/zappy_server_src/core/commands/look_utils.c
  src/zappy_server_src/core/include/command_hold.h
  src/zappy_server_src/core/include/server.h
  src/zappy_server_src/core/server_data.c
Labels: Bug, Refactoring

#173 ClientAI - Parse Broadcast text
  src/zappy_ai_src/ai_broadcast_to_object.py
  src/zappy_ai_src/ai_strategy_management.py
Labels: Pull Request, Implementing

#176 G UI/display assets
  src/zappy_gui_src/Core/Animation/Animation.cpp
  src/zappy_gui_src/Core/Animation/Animation.hpp
  src/zappy_gui_src/Core/Core.cpp
  src/zappy_gui_src/Core/SFML/Interface/Inventory/Inventory.cpp
  src/zappy_gui_src/Core/SFML/Interface/Minimap/Minimap.hpp
  src/zappy_gui_src/Core/SFML/Map/CMakeLists.txt
  src/zappy_gui_src/Core/SFML/Map/Map.cpp
  src/zappy_gui_src/Core/SFML/Map/Map.hpp
Labels: Documentation, Pull Request, Implementing

#175 ClientAI - Hotfix for the __waitForAction method
  src/zappy_ai_src/ai_strategy_management.py
Labels: Bug, Refactoring

#179 142/HotFix - Epitech Coding Style
  src/zappy_ai_src/network/CMakeLists.txt
  src/zappy_ai_src/network/api/include/intern_data.h
  src/zappy_ai_src/network/net_utils/CMakeLists.txt
  src/zappy_gui_src/Core/Network/CMakeLists.txt
  src/zappy_gui_src/Core/Network/api/CMakeLists.txt
  src/zappy_gui_src/Core/Network/api/get/retcode.c
  src/zappy_gui_src/Core/Network/api/get/unexpected.c
  src/zappy_gui_src/Core/Network/api/include/intern_data.h
  src/zappy_gui_src/Core/Network/net_utils/CMakeLists.txt
  src/zappy_server_src/core/command_hold.c
  src/zappy_server_src/core/commands/broadcast_process.c
  src/zappy_server_src/core/commands/connectnbr_command.c
  src/zappy_server_src/core/commands/entity_info.c
  src/zappy_server_src/core/commands/fork_utils.c
  src/zappy_server_src/core/commands/incantation_command.c
  src/zappy_server_src/core/commands/look_command.c
  src/zappy_server_src/core/commands/look_process.c
  src/zappy_server_src/core/container_utils.c
  src/zappy_server_src/core/entity/entity_delete.c
  src/zappy_server_src/core/entity/entity_wrapper.c
  src/zappy_server_src/core/entity/entity_wrapper_create.c
  src/zappy_server_src/core/entity/pack.c
  src/zappy_server_src/core/entity/pack_get_len.c
  src/zappy_server_src/core/entity/player.c
  src/zappy_server_src/core/include/command_hold.h
  src/zappy_server_src/core/include/container.h
  src/zappy_server_src/core/include/entity/pack.h
  src/zappy_server_src/core/include/entity/player.h
  src/zappy_server_src/core/include/entity/tile.h
  src/zappy_server_src/core/include/entrypoint.h
  src/zappy_server_src/core/include/incantation.h
  src/zappy_server_src/core/include/map.h
  src/zappy_server_src/core/include/rcodes.h
  src/zappy_server_src/core/include/remove_inventory.h
  src/zappy_server_src/core/include/server.h
  src/zappy_server_src/core/include/team.h
  src/zappy_server_src/core/map_utils.c
  src/zappy_server_src/core/server_run.c
  src/zappy_server_src/net_utils/CMakeLists.txt
  src/zappy_server_src/net_utils/fd_sets_manage/CMakeLists.txt
  src/zappy_server_src/net_utils/include/net_utils.h
  tests/ai_functionnal_test.c
  tests/gui_functionnal_test.c
Labels: Refactoring

#181 [*] Fix doxyfile
  Doxyfile
Labels: Documentation, Pull Request, Refactoring

#188 142/HotFix - AI Api Overflow
  src/zappy_ai_src/network/net_utils/fetch_message.c
Labels: Bug, Refactoring

#178 GUI/menus/add scroll/172
  src/zappy_gui_src/Core/SFML/Interface/Interface.cpp
  src/zappy_gui_src/Core/SFML/Interface/Inventory/Inventory.cpp
  src/zappy_gui_src/Core/SFML/Interface/Inventory/Inventory.hpp
  src/zappy_gui_src/Core/SFML/Interface/ServerCommunication/ServerCommunication.cpp
  src/zappy_gui_src/Core/SFML/Interface/ServerCommunication/ServerCommunication.hpp
  src/zappy_gui_src/Core/SFML/SFML.cpp
  src/zappy_gui_src/Core/SFML/WrapperSFML/Event.hpp
Labels: Pull Request

#184 GUI/sound design/182
  assets/death.wav
  assets/egg.wav
  assets/lose.wav
  assets/spawn.wav
  assets/test.ogg
  assets/win.wav
  src/zappy_gui_src/Core/SFML/Map/Map.cpp
  src/zappy_gui_src/Core/SFML/Map/Map.hpp
  src/zappy_gui_src/Core/SFML/WrapperSFML/CMakeLists.txt
  src/zappy_gui_src/Exception/ZappyGuiException.cpp
  src/zappy_gui_src/Exception/ZappyGuiException.hpp
Labels: Documentation, Pull Request, Implementing

#189 GUI/map/improve default view
  assets/deraumere.png
  assets/egg.png
  assets/food.png
  assets/ground1.png
  assets/linemate.png
  assets/mendiane.png
  assets/phiras.png
  assets/sibur.png
  assets/thystame.png
  assets/woman1.png
  assets/woman2.png
  assets/woman3.png
  assets/woman4.png
  src/zappy_gui_src/Core/SFML/Interface/Interface.cpp
  src/zappy_gui_src/Core/SFML/Interface/Inventory/Inventory.cpp
  src/zappy_gui_src/Core/SFML/Interface/Inventory/Inventory.hpp
  src/zappy_gui_src/Core/SFML/Map/Map.cpp
  src/zappy_gui_src/Core/SFML/Map/Map.hpp
  src/zappy_gui_src/Core/SFML/SFML.cpp
Labels: Pull Request

#187 GUI/Core/Parse Status/185
  src/zappy_gui_src/Core/Core.cpp
  src/zappy_gui_src/Core/Entity/Entity.hpp
  src/zappy_gui_src/Core/Network/Unpack.cpp
  src/zappy_gui_src/Core/Network/Unpack.hpp
  src/zappy_gui_src/Core/SFML/Map/Map.hpp
  src/zappy_gui_src/Core/SFML/SFML.hpp
Labels: Documentation, Pull Request, Implementing

#191 Makefile implementation
  .gitignore
  Makefile
Labels: Implementing

#193 [+] Add resized logo and update readme.md
  README.md
  docs/assets/logo/logo_100_100.png
  docs/assets/logo/logo_303_289.png
Labels: Documentation

#192 Opti/send modified entities
  .gitignore
  src/zappy_ai_src/network/api/authentification.c
  src/zappy_gui_src/Core/Core.cpp
  src/zappy_gui_src/Core/Entity/Entity.hpp
  src/zappy_gui_src/Core/Network/Unpack.cpp
  src/zappy_gui_src/Core/SFML/Interface/Interface.hpp
  src/zappy_gui_src/Core/SFML/Interface/Minimap/Minimap.cpp
  src/zappy_gui_src/Core/SFML/Interface/ServerCommunication/ServerCommunication.cpp
  src/zappy_gui_src/Core/SFML/Interface/ServerCommunication/ServerCommunication.hpp
  src/zappy_gui_src/Core/SFML/Map/Map.cpp
  src/zappy_gui_src/Core/SFML/Map/Map.hpp
  src/zappy_gui_src/Core/SFML/Map/Tile.cpp
  src/zappy_gui_src/Core/SFML/Map/Tile.hpp
  src/zappy_gui_src/Core/SFML/SFML.hpp
  src/zappy_server_src/core/CMakeLists.txt
  src/zappy_server_src/core/commands/eject_command.c
  src/zappy_server_src/core/commands/entity_info.c
  src/zappy_server_src/core/commands/fork_command.c
  src/zappy_server_src/core/commands/fork_utils.c
  src/zappy_server_src/core/commands/forward_command.c
  src/zappy_server_src/core/commands/incantation_command.c
  src/zappy_server_src/core/commands/join_command.c
  src/zappy_server_src/core/commands/look_command.c
  src/zappy_server_src/core/commands/map_info.c
  src/zappy_server_src/core/commands/place_command.c
  src/zappy_server_src/core/commands/start_information.c
  src/zappy_server_src/core/commands/take_command.c
  src/zappy_server_src/core/commands/turn_command.c
  src/zappy_server_src/core/container_utils.c
  src/zappy_server_src/core/entity/CMakeLists.txt
  src/zappy_server_src/core/entity/egg.c
  src/zappy_server_src/core/entity/entity_diff.c
  src/zappy_server_src/core/entity/pack.c
  src/zappy_server_src/core/entity/player.c
  src/zappy_server_src/core/include/command_hold.h
  src/zappy_server_src/core/include/entity/eggs.h
  src/zappy_server_src/core/include/entity/entity.h
  src/zappy_server_src/core/include/entity/pack.h
  src/zappy_server_src/core/include/entity/player.h
  src/zappy_server_src/core/include/map.h
  src/zappy_server_src/core/include/server.h
  src/zappy_server_src/core/map.c
  src/zappy_server_src/core/my_zappy_server.c
  src/zappy_server_src/core/player_life.c
  src/zappy_server_src/core/resource_generation.c
  src/zappy_server_src/core/scheduler_delete.c
  src/zappy_server_src/core/server_data.c
  src/zappy_server_src/core/server_init.c
  src/zappy_server_src/core/server_run.c
  src/zappy_server_src/entrypoint.c
Labels: Pull Request

#198 142/hot fix/optimisation
  src/zappy_server_src/core/commands/join_command.c
  src/zappy_server_src/core/commands/map_info.c
  src/zappy_server_src/core/server_data.c
Labels: Refactoring

#200 142/HotFix - Look
  src/zappy_ai_src/network/api/ask/broadcast.c
  src/zappy_ai_src/network/api/ask/connectnbr.c
  src/zappy_ai_src/network/api/ask/eject.c
  src/zappy_ai_src/network/api/ask/forward.c
  src/zappy_ai_src/network/api/ask/incantation.c
  src/zappy_ai_src/network/api/ask/inventory.c
  src/zappy_ai_src/network/api/ask/join.c
  src/zappy_ai_src/network/api/ask/look.c
  src/zappy_ai_src/network/api/ask/place.c
  src/zappy_ai_src/network/api/ask/send_request.c
  src/zappy_ai_src/network/api/ask/take.c
  src/zappy_ai_src/network/api/ask/turn.c
  src/zappy_ai_src/network/api/authentification.c
  src/zappy_ai_src/network/api/get/broadcast.c
  src/zappy_ai_src/network/api/get/connectnbr.c
  src/zappy_ai_src/network/api/get/eject.c
  src/zappy_ai_src/network/api/get/fork.c
  src/zappy_ai_src/network/api/get/forward.c
  src/zappy_ai_src/network/api/get/incantation.c
  src/zappy_ai_src/network/api/get/inventory.c
  src/zappy_ai_src/network/api/get/place.c
  src/zappy_ai_src/network/api/get/retcode.c
  src/zappy_ai_src/network/api/get/take.c
  src/zappy_ai_src/network/api/get/turn.c
  src/zappy_ai_src/network/api/get/unexpected.c
  src/zappy_gui_src/Core/Network/api/ask/restart.c
  src/zappy_gui_src/Core/Network/api/authentification.c
  src/zappy_gui_src/Core/Network/api/get/restart.c
  src/zappy_server_src/core/cmake_error.c
  src/zappy_server_src/core/command_hold.c
  src/zappy_server_src/core/commands/broadcast_process.c
  src/zappy_server_src/core/commands/game_status.c
  src/zappy_server_src/core/commands/look_process.c
  src/zappy_server_src/core/commands/look_utils.c
  src/zappy_server_src/core/end_game_gestion.c
  src/zappy_server_src/core/entity/player.c
  src/zappy_server_src/core/include/entity/pack.h
Labels: Bug

#201 142/HotFix - Forward Eject
  src/zappy_server_src/core/commands/eject_command.c
  src/zappy_server_src/core/commands/forward_command.c
Labels: Bug

#202 142/HotFix - Look Broadcast
  src/zappy_server_src/core/commands/look_utils.c
  src/zappy_server_src/core/include/broadcast.h
Labels: Bug

#203 142/HotFix - Entity Modified List
  src/zappy_server_src/core/entity/CMakeLists.txt
  src/zappy_server_src/core/entity/entity_diff_remove.c
  src/zappy_server_src/core/include/entity/entity.h
  src/zappy_server_src/core/player_life.c
  src/zappy_server_src/core/server_data.c
Labels: Bug

#195 GUI - Minimap
  assets/black_woman1.png
  assets/black_woman2.png
  assets/black_woman3.png
  assets/black_woman4.png
  assets/diapo background 2.png
  assets/diapo background 3.png
  assets/diapo background.png
  assets/ground1.png
  assets/logo.png
  assets/pink_woman1.png
  assets/pink_woman2.png
  assets/pink_woman3.png
  assets/pink_woman4.png
  assets/purple_woman1.png
  assets/purple_woman2.png
  assets/purple_woman3.png
  assets/purple_woman4.png
  assets/woman1.png
  assets/woman2.png
  assets/woman3.png
  assets/woman4.png
  assets/yellow_woman1.png
  assets/yellow_woman2.png
  assets/yellow_woman3.png
  assets/yellow_woman4.png
  src/zappy_gui_src/Core/SFML/Interface/Interface.hpp
  src/zappy_gui_src/Core/SFML/Interface/Minimap/Minimap.cpp
  src/zappy_gui_src/Core/SFML/Interface/Minimap/Minimap.hpp
  src/zappy_gui_src/Core/SFML/Interface/ServerCommunication/ServerCommunication.cpp
  src/zappy_gui_src/Core/SFML/Interface/ServerCommunication/ServerCommunication.hpp
  src/zappy_gui_src/Core/SFML/Map/Map.cpp
Labels: Pull Request

#204 ClientAI - Add Unitary Tests
  .gitignore
  src/zappy_ai_src/zappyAIArgumentsTester.sh
  src/zappy_ai_src/zappy_ai_tests/test_ai_handle_response
  tests/CMakeLists.txt
  tests/zappy_ai_tests/CMakeLists.txt
  tests/zappy_ai_tests/test_function_wrapper.py
  tests/zappy_ai_tests/test_inventory.py
  tests/zappy_ai_tests/test_lib_wrapper.py
  tests/zappy_ai_tests/test_map.py
Labels: Pull Request, Implementing

#206 Fix some issues
  assets/white_woman1.png
  assets/white_woman2.png
  assets/white_woman3.png
  assets/white_woman4.png
  src/zappy_gui_src/Core/SFML/Interface/Inventory/Inventory.cpp
  src/zappy_gui_src/Core/SFML/Interface/Minimap/Minimap.cpp
  src/zappy_gui_src/Core/SFML/Interface/Minimap/Minimap.hpp
  src/zappy_gui_src/Core/SFML/Map/Map.cpp
  src/zappy_gui_src/Core/SFML/Map/Map.hpp
Labels: Pull Request

#205 GUI/tests
  src/zappy_gui_src/Core/Network/Unpack.cpp
  tests/unit_tests/CMakeLists.txt
  tests/unit_tests/gui_unpack/CMakeLists.txt
  tests/unit_tests/gui_unpack/TestsUnpack.cpp
Labels: Pull Request, Implementing

#208 GUI/fix last issues
  assets/white_woman1.png
  assets/white_woman2.png
  assets/white_woman3.png
  assets/white_woman4.png
  src/zappy_gui_src/Core/SFML/Interface/Interface.hpp
  src/zappy_gui_src/Core/SFML/Map/Map.cpp
  src/zappy_gui_src/Core/SFML/SFML.cpp
  src/zappy_gui_src/Core/SFML/SFML.hpp
Labels: Pull Request

#207 Ai make aggressive moves
  src/zappy_ai_src/ai_strategy_management.py
  src/zappy_ai_src/ai_strategy_mode.py
Labels: Server - App

#209 fix player color
  src/zappy_gui_src/Core/SFML/Map/Map.cpp
Labels: Pull Request
